# Generated by Django 4.1.7 on 2023-08-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=1000)),
                ('weight', models.CharField(max_length=1000)),
                ('sex', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=110)),
                ('disease', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
