# Generated by Django 4.1.7 on 2023-08-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='medical_history',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
