# Generated by Django 4.1.7 on 2023-08-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_medical_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='medical_history',
        ),
    ]
